version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: "Dockerfile-frontend"
    ports:
      - "80:80"
    links:
      - spboot  
  spboot:
    build:
      context: .
      dockerfile: "Dockerfile-spboot"
    ports:
      - "8083:8080"
    links:
      - mssql  
  mssql:
    build:
      context: .
      dockerfile: "Dockerfile-mssql"
    ports:
      - "1433:1433"