version: '3'
services:
  webservice:
    build:
      context: .
      dockerfile: "Dockerfile-mongo"
    ports:
      - "27017:27017"
  angular:
    build:
      context: .
      dockerfile: "Dockerfile-weblogic"
    ports:
      - "7001:7001"
      - "7002:7002"
    links:
      - mssql
  mssql:
    build:
      context: .
      dockerfile: "Dockerfile-mssql"
    ports:
      - "1433:1433"