version: '3'
services:
  spboot:
    build:
      context: .
      dockerfile: "Dockerfile-spboot"
    ports:
      - "8083:8080"
    links:
      - mssql  
  mssql:
    build:
      context: .
      dockerfile: "Dockerfile-mssql"
    ports:
      - "1433:1433"